// export { default as admin } from '#conf/admin'
// export { default as alias } from '#conf/alias'
// export { default as approve } from '#conf/approve'
// export { default as branch } from '#conf/branch'
// export { default as build } from '#conf/build'
// export { default as clean } from '#conf/clean'
// export { default as cleanbranch } from '#conf/cleanbranch'
// export { default as combine } from '#conf/combine'
// export { default as continue } from '#conf/continue'
// export { default as copy } from '#conf/copy'
// export { default as end } from '#conf/end'
// export { default as get } from '#conf/get'
// export { default as go } from '#conf/go'
// export { default as hook } from '#conf/hook'
// export { default as install } from '#conf/install'
// export { default as link } from '#conf/link'
// export { default as log } from '#conf/log'
// export { default as postmsg } from '#conf/postmsg'
// export { default as redo } from '#conf/redo'
// export { default as revert } from '#conf/revert'
// export { default as review } from '#conf/review'
// export { default as run } from '#conf/run'
// export { default as save } from '#conf/save'
// export { default as start } from '#conf/start'
// export { default as status } from '#conf/status'
// export { default as suggest } from '#conf/suggest'
// export { default as ui } from '#conf/ui'
// export { default as undo } from '#conf/undo'
// export { default as unlink } from '#conf/unlink'
// export { default as update } from '#conf/update'
// export { default as upgrade } from '#conf/upgrade'

export { default as admin } from './admin.mjs'
export { default as alias } from './alias.mjs'
export { default as approve } from './approve.mjs'
export { default as branch } from './branch.mjs'
export { default as build } from './build.mjs'
export { default as clean } from './clean.mjs'
export { default as cleanbranch } from './cleanbranch.mjs'
export { default as combine } from './combine.mjs'
export { default as continue } from './continue.mjs'
export { default as copy } from './copy.mjs'
export { default as end } from './end.mjs'
export { default as get } from './get.mjs'
export { default as go } from './go.mjs'
export { default as hook } from './hook.mjs'
export { default as install } from './install.mjs'
export { default as link } from './link.mjs'
export { default as log } from './log.mjs'
export { default as postmsg } from './postmsg.mjs'
export { default as redo } from './redo.mjs'
export { default as revert } from './revert.mjs'
export { default as review } from './review.mjs'
export { default as run } from './run.mjs'
export { default as save } from './save.mjs'
export { default as start } from './start.mjs'
export { default as status } from './status.mjs'
export { default as suggest } from './suggest.mjs'
export { default as ui } from './ui.mjs'
export { default as undo } from './undo.mjs'
export { default as unlink } from './unlink.mjs'
export { default as update } from './update.mjs'
export { default as upgrade } from './upgrade.mjs'
