/** Declaration file generated by dts-gen */

// declare var lowdb: debug.lowdb & { lowdb: lowdb.lowdb; default: lowdb.lowdb }

// export = lowdb
// export as namespace lowdb

// declare namespace lowdb {
//     export function lowdb(adapter: any): any
// }

// declare module 'lowdb' {
//     export function lowdb(adapter: any): any
// }

declare function lowdb(adapter: any): any

// declare module 'lowdb/adapters/FileSync.js' {
//     export function FileSync(base: any): any
// }
