Object.defineProperty(exports, '__esModule', { value: true })

// isHusky
export function isHusky(data: string): boolean {
    return data.includes('# husky') || data.includes('#husky')
}

// isGitmars
export function isGitmars(data: string): boolean {
    return data.includes('# gitmars')
}

// isYorkie
export function isYorkie(data: string): boolean {
    return data.includes('#yorkie')
}

// isGhooks
export function isGhooks(data: string): boolean {
    return data.includes('// Generated by ghooks. Do not edit this file.')
}

// isPreCommit
export function isPreCommit(data: string): boolean {
    return data.includes('./node_modules/pre-commit/hook')
}

export default {
    isHusky,
    isGitmars,
    isYorkie,
    isGhooks,
    isPreCommit
}
