import { describe, expect, it } from 'vitest'
import { isGhooks, isGitmars, isHusky, isPreCommit, isYorkie } from '../src/getHookType.js'

describe('getHookType', () => {
	describe('isHusky', () => {
		it('should return true for husky hooks', () => {
			expect(isHusky('# husky\n#!/bin/sh')).toBeTruthy()
			expect(isHusky('#husky\n#!/bin/sh')).toBeTruthy()
		})

		it('should return false for non-husky hooks', () => {
			expect(isHusky('#!/bin/sh')).toBeFalsy()
			expect(isHusky('# gitmars hook')).toBeFalsy()
		})

		it('should handle empty string', () => {
			expect(isHusky('')).toBeFalsy()
		})
	})

	describe('isGitmars', () => {
		it('should return true for gitmars hooks', () => {
			expect(isGitmars('# gitmars\n#!/bin/sh')).toBeTruthy()
		})

		it('should return false for non-gitmars hooks', () => {
			expect(isGitmars('#!/bin/sh')).toBeFalsy()
			expect(isGitmars('# husky\n#!/bin/sh')).toBeFalsy()
		})

		it('should handle empty string', () => {
			expect(isGitmars('')).toBeFalsy()
		})
	})

	describe('isYorkie', () => {
		it('should return true for yorkie hooks', () => {
			expect(isYorkie('#yorkie\n#!/bin/sh')).toBeTruthy()
		})

		it('should return false for non-yorkie hooks', () => {
			expect(isYorkie('#!/bin/sh')).toBeFalsy()
			expect(isYorkie('# husky\n#!/bin/sh')).toBeFalsy()
		})

		it('should handle empty string', () => {
			expect(isYorkie('')).toBeFalsy()
		})
	})

	describe('isGhooks', () => {
		it('should return true for ghooks hooks', () => {
			expect(isGhooks('// Generated by ghooks. Do not edit this file.\n#!/bin/sh')).toBeTruthy()
		})

		it('should return false for non-ghooks hooks', () => {
			expect(isGhooks('#!/bin/sh')).toBeFalsy()
			expect(isGhooks('# husky\n#!/bin/sh')).toBeFalsy()
		})

		it('should handle empty string', () => {
			expect(isGhooks('')).toBeFalsy()
		})
	})

	describe('isPreCommit', () => {
		it('should return true for pre-commit hooks', () => {
			expect(isPreCommit('./node_modules/pre-commit/hook')).toBeTruthy()
		})

		it('should return false for non-pre-commit hooks', () => {
			expect(isPreCommit('#!/bin/sh')).toBeFalsy()
			expect(isPreCommit('# husky\n#!/bin/sh')).toBeFalsy()
		})

		it('should handle empty string', () => {
			expect(isPreCommit('')).toBeFalsy()
		})
	})
})
