'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

Object.defineProperty(exports, '__esModule', {
  value: true
});
function isHusky(data) {
  return data.indexOf('# husky') > -1 || data.indexOf('#husky') > -1;
}
function isGitmars(data) {
  return data.indexOf('# gitmars') > -1;
}
function isYorkie(data) {
  return data.indexOf('#yorkie') > -1;
}
function isGhooks(data) {
  return data.indexOf('// Generated by ghooks. Do not edit this file.') > -1;
}
function isPreCommit(data) {
  return data.indexOf('./node_modules/pre-commit/hook') > -1;
}
var getHookType = {
  isHusky,
  isGitmars,
  isYorkie,
  isGhooks,
  isPreCommit
};

exports['default'] = getHookType;
exports.isGhooks = isGhooks;
exports.isGitmars = isGitmars;
exports.isHusky = isHusky;
exports.isPreCommit = isPreCommit;
exports.isYorkie = isYorkie;
